name: subnetwork_inference
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - numpy=1.24.1
  - scikit-learn=1.2.0
  - polars=0.15.14
  - jupyterlab=3.5.3
  - notebook=6.5.2
  - matplotlib=3.6.3
  - plotly=5.13.0
  - pyarrow=12.0.0
  - python-kaleido=0.2.1
  - tqdm=4.64.1
  - ipywidgets=7.6.5
  - tensorboard=2.11.2
  - hydra-core=1.3.2
  - pip:
    - laplace-torch
