name: subnetwork_inference
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.2.2
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - numpy=1.24.3
  - scikit-learn=1.2.2
  - tqdm=4.65.0
  - hydra-core=1.3.2
  - Pillow=9.4.0

  - pip:
    - laplace-torch
