seed: 9

model:
  architecture: resnet18
  p_drop: 0

data:
  seed: 9
  path: data/Image
  name: MNIST
  workers: 4
  val_size: 0.15

trainer:
  epochs: 90
  lr: 0.1
  momentum: 0.9
  weight_decay: 1E-4
  milestones:
    - 40
    - 70
  gamma: 0.1
  batch_size: 2048
  checkpoint_path: checkpoints/mnist
  results_path: results/mnist
  model_type: MAP
  la:
    subset_of_weights: all
    hessian_structure: diag 
    selection_strategy: LVD
    subset_size: 0
    prior_mean: 0.0
    sigma_noise: 1.0
    

