seed: 9
version: 9

train_map: True
train_la: True

data:
  seed: 9
  path: data
  name: Kin8nm
  val_size: 0.15
  split_index: 1
  gap: True

model:
  input_size: 8
  hidden_sizes:
    - 50
    - 50
  output_size: 1

trainer:
  epochs: 2000
  patience: 100
  lr: 1e-3
  batch_size: 32
  checkpoint_path: checkpoints
  results_path: results
  la:
    posthoc: True
    subset_of_weights:
      - all
    hessian_structure:
      - full
      - diag
      - kron    
    weight_proportion: 1.0
    selection_strategy: random
    prior_mean: 0.0
    epochs: 100
    lr: 1e-3


