seed: 99

data:
  seed: 99
  path: data
  name: wine
  val_size: 0.15
  split: GAP
  split_index: 1
  

model:
  hidden_sizes:
    - 50
    - 50

trainer:
  epochs: 2000
  patience: 100
  lr: 1e-3
  batch_size: 32
  checkpoint_path: checkpoints
  results_path: results
  model_type: LA_POSTHOC
  la:
    subset_of_weights: subnetwork
    hessian_structure: full 
    selection_strategy: LVD
    subset_size: 600
    prior_mean: 0.0


